### PR TITLE
use language: julia on travis

### PR DESCRIPTION
**Pull request by tkelman**
the ppa does not allow for easy testing on 0.3 any more

### CODE REVIEW

**Comment by tkelman** [comment]
As I thought might happen, your most recent tag is broken on Julia 0.3. There's a right way to drop support for 0.3, but you'd need to adjust the version in REQUIRE and use a new minor version number for the package. Looks like it's rescuable without too much trouble. I can squash these commits if you'd prefer, just let me know.

**Comment by richardreeve** [comment]
No, that's great - thanks. I don't have 0.3 available to me any longer, and I could find it to download. I feared that the Union fix (at least) would break it, but I didn't know about Compat.

**Comment by tkelman** [comment]
Links for the old binaries should still work at http://julialang.org/downloads/oldreleases.html.

**Comment by richardreeve** [comment]
Ah, that's great, thanks. I never found a link to that page.

**Pull request merged**
